version: 2

models:
  - name: dim_listings_cleaned
    description: Cleaned table which contains dbt_listings
    columns:

    - name: listing_id
      decription: Primary_key for the listing
      tests:
        - unique
        - not_null

    - name: host_id
      description: Host Id's id, referrences the Dim_hosts table
      tests:
        - not_null
        #  this relationship part says every host_id value is a valid reference from dim_host_cleaned table's host_id column
        - relationships:
            to: ref('dim_hosts_cleaned')
            field: host_id

    - name: room_type
      description: Type of Apartment/Room
      tests:
        - accepted_values: 
            values: ['Entire home/apt', 
                     'Private room',
                     'Shared room',
                     'Hotel room'

                    ]

    - name: minimum_nights
      description: '{{doc("dim_listing_cleaned_minimum_nights")}}'
      tests: 
        - positive_value
  
  - name: dim_hosts_cleaned
    description: Description of the Dim host table

  - name: dim_listings_with_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table_times_factor:
          compare_model: source('airbnb','listings')
    columns:
      - name: price
        tests: 
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn 

      
  