#  this defines the sources and abstraction when referring to the source table

version: 2

sources:
  - name: airbnb
    schema: raw  # data schema where we are picking data
    tables:       # list of raw tables
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"

      - name: hosts
        identifier: raw_hosts
      
      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date   # this checks the source freshness of the table
        freshness: 
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}